### ISSUE TITLE
jdk 8 error in `parse_app_dir_name'

### ISSUE THREAD

**Issue by PatrickHennig** [agileorbit-cookbooks/java#275]
Hi, 

I tried to install jdk_version 8 with oracle.
But it always fails with: 

Do you have any idea why?
```
NoMethodError
-------------
undefined method `split' for nil:NilClass
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/java/providers/ark.rb:28:in `parse_app_dir_name'
/var/lib/aws/opsworks/cache.stage2/cookbooks/java/providers/ark.rb:86:in `block in class_from_file'
```
Best Regards, 
Patrick

**Comment by erichelgeson** [comment]
You've provided no details on how you are using the cookbook, so I will guess you passed in a filename to java_ark that is nil or causes this object (referenced in your trace) to be nil https://github.com/agileorbit-cookbooks/java/blob/master/providers/ark.rb#L28

Please take a look at https://github.com/agileorbit-cookbooks/java/blob/master/ISSUES.md on what to provide when creating an issue.

**Comment by PatrickHennig** [comment]
Sorry, I'm using OpWorks with Chef 11.10 on an Amazon Linux 2015.3 System and try to install version 8 of Java.
I only changed the jdk_version from 7 to 8 in my custom JSON. 

I understand where it happens, at ark.rb:28 at the split because url is Nil. But why? Even if I put the jdk_version at the wrong position it should be default and not nil.

And in the default.rb in the attributes folder there is the url specified for 8.

Best regards,
Patrick

**Comment by erichelgeson** [comment]
That is true about nil on slice. Can you provide a full working example of what you include and how? Something must not be loaded at the correct time. I've used this previously on opsworks chef 11.10

**Comment by PatrickHennig** [comment]
I use the opsworks-elasticsearch-cookbook for installing elastic search with enabled Berksfile.

Hereby I use this custom JSON:
{  
   "java":{  
      "jdk_version":"8",
      "accept_license_agreement":"true",
      "install_flavor":"oracle",
      "oracle":{  
         "accept_oracle_download_terms":"true"
      }
   },
   "elasticsearch":{  
      "version":"1.5.2",
      "nginx":{  
         "port":"80",
         "users":[  
            {  
               "username":"username",
               "password":"password"
            }
         ],
         "allow_cluster_api":"true"
      },
      "gateway":{  
         "expected_nodes":"3"
      },
      "path":{  
         "data":"/mnt/elasticsearch-data"
      },
      "cluster":{  
         "name":"opsworks-elasticsearch"
      },
      "cloud":{  
         "aws":{  
            "region":"us-east-1"
         }
      },
      "custom_config":{  
         "cluster.routing.allocation.awareness.attributes":"rack_id"
      },
      "discovery":{  
         "ec2":{  
            "tag":{  
               "opsworks:stack":"ES"
            }
         },
         "zen":{  
            "minimum_master_nodes":"2",
            "ping":{  
               "multicast":{  
                  "enabled":"false"
               }
            }
         },
         "type":"ec2"
      }
   }
}

**Comment by sivalingams** [comment]
Hi Patrick,

The issue is not with this java cookbook.

In https://github.com/awslabs/opsworks-elasticsearch-cookbook/blob/master/Berksfile#L7
> cookbook 'java', '>= 1.19.2', git: 'git://github.com/opscode-cookbooks/java.git', tag: 'v1.21.2'

Oracle JDK 1.8 support was not in that version(v1.21.2) of cookbook. The support for Oracle JDK 1.8 was introduced with version v1.22.0. For now, the latest release version is v1.31.0

You can fork opsworks-elasticsearch-cookbook and change the line.
> cookbook 'java', '>= 1.31.0', git: 'git://github.com/opscode-cookbooks/java.git', tag: 'v1.31.0'

I checked myself and its working. :+1:

**Comment by erichelgeson** [comment]
Thanks @sivalingams for catching that! Please re-open the issue @PatrickHennig if that is not the case after bumping to the latest java cookbook version
